version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: monshop
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d monshop"]
      interval: 5s
      timeout: 5s
      retries: 10
  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: app
      DB_PASS: app
      DB_NAME: monshop
      ADMIN_USER: ${ADMIN_USER:-admin}
      ADMIN_PASS: ${ADMIN_PASS:-change-me}
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ./frontend
    depends_on: [backend]
    expose:
      - "80"
volumes:
  dbdata:
