services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: monshop
    volumes: [dbdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U app"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    env_file: [.env]
    depends_on: [db]
    expose: ["4000"]

  frontend:
    build: ./frontend
    depends_on: [backend]
    expose: ["80"]

  caddy:
    image: caddy:2
    ports: ["80:80","443:443"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddydata:/data
      - caddyconfig:/config
    depends_on: [frontend, backend]

volumes:
  dbdata:
  caddydata:
  caddyconfig:
