services:
  backend:
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:4000/health >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
  frontend:
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
