services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monshop
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uapp -papp --silent"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: app
      DB_PASS: app
      DB_NAME: monshop
      ADMIN_USER: ${ADMIN_USER:-admin}
      ADMIN_PASS: ${ADMIN_PASS:-change-me}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    depends_on: [backend]
    ports:
      - "8080:80"

volumes:
  db_data:
