services:
  frontend:
    ports:
      - "8080:80"
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  backend:
    volumes:
      - ./backend/routes:/app/routes
      - ./backend/app.js:/app/app.js:ro
