name: CI Smoke
on:
  push:
  pull_request:
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/setup-qemu-action@v3
      - name: Build & Up
        run: docker compose up -d --build
      - name: Wait for services
        run: |
          BPORT="$(docker compose port backend 4000 | sed 's/.*://')"
          FPORT="$(docker compose port frontend 80   | sed 's/.*://')"
          for i in $(seq 1 30); do curl -fsS "http://127.0.0.1:${BPORT}/api/health" && break || sleep 1; done
          for i in $(seq 1 30); do curl -fsS "http://127.0.0.1:${FPORT}/" && break || sleep 1; done
      - name: Run smoke script
        run: ./scripts/smoke-v2.sh
