name: CI
on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build
        run: docker compose build
      - name: Up
        run: docker compose up -d
      - name: Smoke
        run: ./scripts/smoke-v2.sh
      - name: Logs on failure
        if: failure()
        run: |
          docker compose ps
          docker compose logs --no-color --tail=200
